### ISSUE TITLE
Convert all .mds in a directory and auto-resolve them

### ISSUE THREAD

**Issue by thechrisu** [TimboKZ/blitz-website#1]
When having A LOT of markdown documents/articles to maintain, it takes a very long time add everything to blitz.yml. Instead, what about specifying a directory to watch, in which we convert all articles.
For this to work, we can maybe assume id=name=content and specify a certain template to render it to?

D'you know what I mean? :D

**Comment by TimboKZ** [comment]
This is more of a [Blitz issue](https://github.com/TimboKZ/blitz/issues), but I will reply here anyway.

This is actually one of the **key** features, which I did not have a chance to document (yet). Blitz website just has a very specific structure and I need to have references to specific pages in the documentation (mostly to have an ID to the most recent quick guide so I can simply update `blitz.yml` and not have to change each page manually. Check out the `Research` page of the attached example project to see directory parsing in action.

I took the liberty of building the website for you using relative URLs and explicit HTML extensions, so you can browse it offline.

[blitz-directory-example.zip](https://github.com/TimboKZ/blitz-website/files/590367/blitz-directory-example.zip)
